#!/bin/bash

echo "#   __________________________                                                           
#
#   < << Welcome to ScsTools>> >                                                                
#    --------------------------                                                          
#    \
#     \
#                                   .::!!!!!!!:.
# .!!!!!:.                        .:!!!!!!!!!!!!
# ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$ 
#      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P 
#      $$$$$##WX!:      .<!!!!UW$$$$  $$$$$$$$# 
#      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$* 
#     ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R* 
#        *$bd$$$$      *$$$$$$$$$$$o+#
#
#
#

"
set -o errexit



source config_file
#try to install require package and hackingTools
:requirePkg:
:hackTools:
if [ $SYS_VERSION == "Linux" ];then
:start:
#when all dependencies are statisfied
#Make a fudge for testing integrity
fudge 25 .4 "Testing integrity"
#then download Metasploit-framework
:msfdownload:linux
rm -rf msfinstall
echo "run msfconsole to check your script"
elif [ $SYS_VERSION == "Darwin" ];then
:msfdownload:macOs
fi


